services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=chainlitdb
      - POSTGRES_USER=chainlit
      - POSTGRES_PASSWORD=chainlitdbpass
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
    - app-network


  chainlit_app:
    build: ./chainlit_app/
    container_name: chainlit_app
    env_file:
      - .env
    environment:
      - POSTGRES_CONNINFO=postgresql+asyncpg://chainlit:chainlitdbpass@postgres:5432/chainlitdb
      # Secret just for demo puposes, never put auth secret here ! Use .env file
      - CHAINLIT_AUTH_SECRET=_T=HE_XfnNipq~j^F,:aRjZMr=T:YN,SOY^fdlOTVyrqXT_VITNACoismx1gf_uB
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - app-network


volumes:
  postgres:

networks:
  app-network:
    driver: bridge